/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ilyes.borbala
 */
public class GameViewGui extends javax.swing.JFrame {

    /**
     * Creates new form GameViewGui
     */
    public GameViewGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCim = new javax.swing.JLabel();
        lblAjtoKep2 = new javax.swing.JLabel();
        lblAjtoKep3 = new javax.swing.JLabel();
        lblAjtoKep1 = new javax.swing.JLabel();
        lblAjtoFelirat2 = new javax.swing.JLabel();
        lblAjtoFelirat1 = new javax.swing.JLabel();
        lblAjtoFelirat3 = new javax.swing.JLabel();
        btnValaszt1 = new javax.swing.JButton();
        btnValaszt3 = new javax.swing.JButton();
        btnValaszt2 = new javax.swing.JButton();
        btnUjJatek = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaKiiras = new javax.swing.JTextArea();
        nvbMenusor = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mniKilepes = new javax.swing.JMenuItem();
        mnUjJatek = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCim.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblCim.setText("   Vetélkedő (Monty Hall) Játék");

        lblAjtoKep2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilyes.borbala\\Documents\\NetBeansProjects\\Vetelkedo\\src\\view\\ajto2.png")); // NOI18N

        lblAjtoKep3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilyes.borbala\\Documents\\NetBeansProjects\\Vetelkedo\\src\\view\\ajto2.png")); // NOI18N

        lblAjtoKep1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilyes.borbala\\Documents\\NetBeansProjects\\Vetelkedo\\src\\view\\ajto2.png")); // NOI18N

        lblAjtoFelirat2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblAjtoFelirat2.setText("II.Ajtó");

        lblAjtoFelirat1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblAjtoFelirat1.setText("I.Ajtó");

        lblAjtoFelirat3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblAjtoFelirat3.setText("III.Ajtó");

        btnValaszt1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        btnValaszt1.setText("Választ");
        btnValaszt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValaszt1ActionPerformed(evt);
            }
        });

        btnValaszt3.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        btnValaszt3.setText("Választ");
        btnValaszt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValaszt3ActionPerformed(evt);
            }
        });

        btnValaszt2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        btnValaszt2.setText("Választ");
        btnValaszt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValaszt2ActionPerformed(evt);
            }
        });

        btnUjJatek.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnUjJatek.setText("Új Játék");

        txtaKiiras.setColumns(20);
        txtaKiiras.setRows(5);
        jScrollPane2.setViewportView(txtaKiiras);

        mnFile.setText("File");

        mniKilepes.setText("Kilépés");
        mnFile.add(mniKilepes);

        nvbMenusor.add(mnFile);

        mnUjJatek.setText("Új Játék");
        nvbMenusor.add(mnUjJatek);

        setJMenuBar(nvbMenusor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCim, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblAjtoFelirat1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAjtoFelirat2)
                        .addGap(59, 59, 59)
                        .addComponent(lblAjtoFelirat3)
                        .addGap(67, 67, 67))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAjtoKep1)
                                    .addComponent(btnValaszt1))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAjtoKep2)
                                    .addComponent(btnValaszt2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(btnValaszt3))
                                    .addComponent(lblAjtoKep3)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                                .addComponent(btnUjJatek, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCim, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAjtoFelirat2)
                        .addComponent(lblAjtoFelirat3))
                    .addComponent(lblAjtoFelirat1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAjtoKep3)
                    .addComponent(lblAjtoKep2)
                    .addComponent(lblAjtoKep1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValaszt1)
                    .addComponent(btnValaszt2)
                    .addComponent(btnValaszt3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUjJatek)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnValaszt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValaszt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnValaszt1ActionPerformed

    private void btnValaszt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValaszt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnValaszt3ActionPerformed

    private void btnValaszt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValaszt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnValaszt2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameViewGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameViewGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameViewGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameViewGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameViewGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUjJatek;
    private javax.swing.JButton btnValaszt1;
    private javax.swing.JButton btnValaszt2;
    private javax.swing.JButton btnValaszt3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAjtoFelirat1;
    private javax.swing.JLabel lblAjtoFelirat2;
    private javax.swing.JLabel lblAjtoFelirat3;
    private javax.swing.JLabel lblAjtoKep1;
    private javax.swing.JLabel lblAjtoKep2;
    private javax.swing.JLabel lblAjtoKep3;
    private javax.swing.JLabel lblCim;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenu mnUjJatek;
    private javax.swing.JMenuItem mniKilepes;
    private javax.swing.JMenuBar nvbMenusor;
    private javax.swing.JTextArea txtaKiiras;
    // End of variables declaration//GEN-END:variables
}
