/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JMenuItem;
import javax.swing.JTextArea;

/**
 *
 * @author ilyes.borbala
 */
public class GameViewGui extends javax.swing.JFrame {

    /**
     * Creates new form GameViewGui
     */
    public GameViewGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCim = new javax.swing.JLabel();
        btnUjJatek = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaKiiras = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        lblAjtoKep2 = new javax.swing.JLabel();
        btnValaszt1 = new javax.swing.JButton();
        btnValaszt2 = new javax.swing.JButton();
        lblAjtoKep1 = new javax.swing.JLabel();
        lblAjtoKep3 = new javax.swing.JLabel();
        btnValaszt3 = new javax.swing.JButton();
        lblAjtoFelirat1 = new javax.swing.JLabel();
        lblAjtoFelirat2 = new javax.swing.JLabel();
        lblAjtoFelirat3 = new javax.swing.JLabel();
        txtfAjtoAllapot1 = new javax.swing.JTextField();
        txtfAjtoAllapot2 = new javax.swing.JTextField();
        txtfAjtoAllapot3 = new javax.swing.JTextField();
        nvbMenusor = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mniKilepes = new javax.swing.JMenuItem();
        mnUjJatek = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCim.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblCim.setText("   Vetélkedő (Monty Hall) Játék");

        btnUjJatek.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnUjJatek.setText("Új Játék");

        txtaKiiras.setColumns(20);
        txtaKiiras.setRows(5);
        jScrollPane2.setViewportView(txtaKiiras);

        lblAjtoKep2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilyes.borbala\\Documents\\NetBeansProjects\\Vetelkedo\\src\\view\\ajto2.png")); // NOI18N

        btnValaszt1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        btnValaszt1.setText("Választ");
        btnValaszt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValaszt1ActionPerformed(evt);
            }
        });

        btnValaszt2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        btnValaszt2.setText("Választ");
        btnValaszt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValaszt2ActionPerformed(evt);
            }
        });

        lblAjtoKep1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilyes.borbala\\Documents\\NetBeansProjects\\Vetelkedo\\src\\view\\ajto2.png")); // NOI18N

        lblAjtoKep3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilyes.borbala\\Documents\\NetBeansProjects\\Vetelkedo\\src\\view\\ajto2.png")); // NOI18N

        btnValaszt3.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        btnValaszt3.setText("Választ");
        btnValaszt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValaszt3ActionPerformed(evt);
            }
        });

        lblAjtoFelirat1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblAjtoFelirat1.setText("I.Ajtó");

        lblAjtoFelirat2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblAjtoFelirat2.setText("II.Ajtó");

        lblAjtoFelirat3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblAjtoFelirat3.setText("III.Ajtó");

        txtfAjtoAllapot1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtfAjtoAllapot1.setText("Zárva");
        txtfAjtoAllapot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfAjtoAllapot1ActionPerformed(evt);
            }
        });

        txtfAjtoAllapot2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtfAjtoAllapot2.setText("Zárva");
        txtfAjtoAllapot2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfAjtoAllapot2ActionPerformed(evt);
            }
        });

        txtfAjtoAllapot3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtfAjtoAllapot3.setText("Zárva");
        txtfAjtoAllapot3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfAjtoAllapot3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblAjtoFelirat1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAjtoFelirat2)
                        .addGap(59, 59, 59)
                        .addComponent(lblAjtoFelirat3)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAjtoKep1)
                            .addComponent(btnValaszt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtfAjtoAllapot1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnValaszt2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnValaszt3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtfAjtoAllapot2)
                                    .addComponent(lblAjtoKep2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblAjtoKep3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtfAjtoAllapot3))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAjtoFelirat2)
                        .addComponent(lblAjtoFelirat3))
                    .addComponent(lblAjtoFelirat1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAjtoKep3)
                    .addComponent(lblAjtoKep2)
                    .addComponent(lblAjtoKep1))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfAjtoAllapot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfAjtoAllapot3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfAjtoAllapot2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValaszt1)
                    .addComponent(btnValaszt2)
                    .addComponent(btnValaszt3))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        mnFile.setText("File");

        mniKilepes.setText("Kilépés");
        mnFile.add(mniKilepes);

        nvbMenusor.add(mnFile);

        mnUjJatek.setText("Új Játék");
        nvbMenusor.add(mnUjJatek);

        setJMenuBar(nvbMenusor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCim, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUjJatek, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCim, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUjJatek)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnValaszt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValaszt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnValaszt1ActionPerformed

    private void btnValaszt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValaszt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnValaszt3ActionPerformed

    private void btnValaszt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValaszt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnValaszt2ActionPerformed

    private void txtfAjtoAllapot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfAjtoAllapot1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfAjtoAllapot1ActionPerformed

    private void txtfAjtoAllapot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfAjtoAllapot2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfAjtoAllapot2ActionPerformed

    private void txtfAjtoAllapot3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfAjtoAllapot3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfAjtoAllapot3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public JButton getBtnValaszt1() {
        return btnValaszt1;
    }

    public JButton getBtnValaszt2() {
        return btnValaszt2;
    }

    public JButton getBtnValaszt3() {
        return btnValaszt3;
    }

    public JButton getBtnUjJatek() {
        return btnUjJatek;
    }

    public JTextArea getTxtaKiiras() {
        return txtaKiiras;
    }

    public JMenuItem getMniKilepes() {
        return mniKilepes;
    }
        public javax.swing.JTextField getTxtfAjtoAllapot1() {
        return txtfAjtoAllapot1;
    }

    public javax.swing.JTextField getTxtfAjtoAllapot2() {
        return txtfAjtoAllapot2;
    }

    public javax.swing.JTextField getTxtfAjtoAllapot3() {
        return txtfAjtoAllapot3;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUjJatek;
    private javax.swing.JButton btnValaszt1;
    private javax.swing.JButton btnValaszt2;
    private javax.swing.JButton btnValaszt3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAjtoFelirat1;
    private javax.swing.JLabel lblAjtoFelirat2;
    private javax.swing.JLabel lblAjtoFelirat3;
    private javax.swing.JLabel lblAjtoKep1;
    private javax.swing.JLabel lblAjtoKep2;
    private javax.swing.JLabel lblAjtoKep3;
    private javax.swing.JLabel lblCim;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenu mnUjJatek;
    private javax.swing.JMenuItem mniKilepes;
    private javax.swing.JMenuBar nvbMenusor;
    private javax.swing.JTextArea txtaKiiras;
    private javax.swing.JTextField txtfAjtoAllapot1;
    private javax.swing.JTextField txtfAjtoAllapot2;
    private javax.swing.JTextField txtfAjtoAllapot3;
    // End of variables declaration//GEN-END:variables
}
